# Generated by Django 5.2.1 on 2025-05-14 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userprofile_user_attendancerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.qrtoken'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='Attendance',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.DeleteModel(
            name='AttendanceToken',
        ),
    ]
