# Generated by Django 5.2.1 on 2025-05-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_attendancerecord_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='Attendance',
            field=models.CharField(default='Absent', max_length=2),
        ),
    ]
