# Generated by Django 5.2.1 on 2025-05-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_attendancerecord_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
