# Generated by Django 5.2.1 on 2025-05-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_attendancerecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='token',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='user',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='uucms',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='qrtoken',
            name='user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
